//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Complain
    {
        public int Id { get; set; }
        public int CustId { get; set; }
        public System.DateTime Date { get; set; }
        public string Status { get; set; }
        public string Description { get; set; }
        public Nullable<int> DriverId { get; set; }
    
        public virtual CustomerMaster CustomerMaster { get; set; }
        public virtual DriverMaster DriverMaster { get; set; }
    }
}
