//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CustomerMaster
    {
        public CustomerMaster()
        {
            this.FeedbackMasters = new HashSet<FeedbackMaster>();
            this.OrderMasters = new HashSet<OrderMaster>();
            this.DailyOrders = new HashSet<DailyOrder>();
            this.Complains = new HashSet<Complain>();
        }
    
        public int CustId { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string Address1 { get; set; }
        public string Address2 { get; set; }
        public string Address3 { get; set; }
        public string Pincode { get; set; }
        public string PhoneNo { get; set; }
        public string EmailID { get; set; }
        public string Gender { get; set; }
        public System.DateTime Birthdate { get; set; }
        public string Password { get; set; }
        public Nullable<int> QuestionID { get; set; }
        public string Answer { get; set; }
        public string Image { get; set; }
        public Nullable<int> Roleid { get; set; }
    
        public virtual ICollection<FeedbackMaster> FeedbackMasters { get; set; }
        public virtual ICollection<OrderMaster> OrderMasters { get; set; }
        public virtual ICollection<DailyOrder> DailyOrders { get; set; }
        public virtual ICollection<Complain> Complains { get; set; }
    }
}
